### ISSUE TITLE
Python errors running examples

### ISSUE THREAD

**Issue by timnewsham** [schumilo/vUSBf#7]
I've been trying to run the examples listed in the help output and mentioned by others in previous bug reports and I get errors in the python code before the test cases even run, for example:

```
$ python vusbf.py -eon 127.0.0.1 1136 payload/panic_1.obj

A KVM/QEMU based USB-fuzzing framework.
Sergej Schumilo, OpenSource Training Spenneberg 2015
Version: 0.2

Type -h for help
EXECUTE OBJECT MODE (NETWORK)
[*] 7 testcase in file "payload/panic_1.obj"
Test #1:
+---------------------------------------------------------+
        FT: 1193        isVendor: ALL
        FT: 12889       idProduct: ALL
        FT: 2   bDeviceClass: ALL
        FT: 2   bInterfaceClass: ALL
        FT: 17  bNumEndpoints: USB_Interface_Descriptor
        FT: 5   bNumInterfaces: USB_Configuration_Descriptor
{'descriptor': 'desc3.txt', 'emulator': 'enumeration'}
REPRODUCE_KEY:
MQoKMTE5M/9pc1ZlbmRvcv9BTEwKMTI4ODn/aWRQcm9kdWN0/0FMTAoy/2JEZXZpY2VDbGFzc/9BTEwKMv9iSW50ZXJmYWNlQ2xhc3P/QUxMCjE3/2JOdW1FbmRwb2ludHP/VVNCX0ludGVyZmFjZV9EZXNjcmlwdG9yCjX/Yk51bUludG
VyZmFjZXP/VVNCX0NvbmZpZ3VyYXRpb25fRGVzY3JpcHRvcgoKZGVzY3JpcHRvcv9kZXNjMy50eHQKZW11bGF0b3L/ZW51bWVyYXRpb24K
+---------------------------------------------------------+

Traceback (most recent call last):
  File "vusbf.py", line 297, in <module>
    main()
  File "vusbf.py", line 253, in main
    parameter_parser(parameter_list)
  File "vusbf.py", line 114, in parameter_parser
    execute_object_process("" + object_file, host=host, port=port)
  File "/home/newsham/src/vUSBf/process/execute_object.py", line 39, in execute_object_process
    emu.setup_payload(e)
  File "/home/newsham/src/vUSBf/usbEmulator.py", line 58, in setup_payload
    data = usbdescFileParser(config.DEV_DESC_FOLDER + payload.get_option("descriptor")).parse()
  File "/home/newsham/src/vUSBf/fileParser.py", line 72, in parse
    newLayer = self.__parseDescriptor(line)
  File "/home/newsham/src/vUSBf/fileParser.py", line 262, in __parseDescriptor
    return self.__parser(desc, data)
  File "/home/newsham/src/vUSBf/fileParser.py", line 235, in __parser
    setattr(desc, split[0], split[1])
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 221, in __setattr__
    return object.__setattr__(self, attr, val)
AttributeError: 'usb_configuration_descriptor' object has no attribute 'bmAttribut'
```

**Comment by timnewsham** [comment]
Errors are caused by an old version of scapy which seems to be more strict about setting attribute names which dont exist in the structure.  Upgrading to latest scapy fixes the issues.
